// lib/nutrients_db.dart
// 앱 내 정적 “영양소 데이터베이스”
// - LABELS: 영양소 한글 라벨
// - DEFICIENCY: 결핍 시 흔히 알려진 이슈(일반 정보, 의료 조언 아님)
// - FOODS: 영양소별 대표 음식 목록 (각 10개)
//
// ✅ 순서: 탄/단/지 → 나머지(식이섬유/당류/포화/콜레스테롤) → 비타민 → 무기질
// ✅ 트랜스지방(fatrn) 제거
// ✅ 콜레스테롤(chole), 인(p) 대표 음식 10개 추가

const Map<String, String> NUTRIENT_LABELS = {
  // 탄단지
  'chocdf': '탄수화물',
  'prot': '단백질',
  'fatce': '지방',

  // 나머지
  'fibtg': '식이섬유',
  'sugar': '당류',
  'fasat': '포화지방',
  'chole': '콜레스테롤',

  // 비타민
  'vita_rae': '비타민A',
  'vitc': '비타민C',
  'vitd': '비타민D',
  'vite': '비타민E',
  'vitk': '비타민K',
  'vitb1': '비타민B1',
  'vitb2': '비타민B2',
  'vitb3': '비타민B3',
  'vitb6': '비타민B6',
  'vitb12': '비타민B12',
  'folate': '엽산',
  'biotin': '비오틴',
  'pantothenic': '비타민B5',

  // 무기질
  'na': '나트륨',
  'k': '칼륨',
  'p': '인',
  'mg': '마그네슘',
  'ca': '칼슘',
  'fe': '철',
  'zn': '아연',
};

// 결핍 일반 정보(간단 안내)
const Map<String, String> NUTRIENT_DEFICIENCY = {
  'prot': '근손실, 피로감, 상처 치유 지연 등이 나타날 수 있어요.',
  'fibtg': '변비, 포만감 저하, 혈당 변동성 증가가 있을 수 있어요.',
  'na': '저나트륨혈증(어지러움·두통·무기력 등) 위험이 있어요.',
  'k': '근육 경련, 피로, 심장 리듬 이상 위험이 있어요.',
  'ca': '뼈 건강 저하(골감소/골다공증 위험 증가), 근육 경련이 있을 수 있어요.',
  'fe': '빈혈(피로·창백·어지러움), 집중력 저하가 있을 수 있어요.',
  'mg': '근육경련, 피로, 수면 문제 및 신경 과민 등이 있을 수 있어요.',
  'zn': '면역저하, 미각/후각 변화, 피부 트러블이 있을 수 있어요.',
  'vitc': '피로·면역저하, 잇몸 출혈, 상처 회복 지연(심하면 괴혈병) 등이 있어요.',
  'vitd': '뼈/면역 건강 저하(어두운 계절·실내생활 시 특히 주의) 위험이 있어요.',
  'vite': '항산화 기능 저하, 근육 약화가 있을 수 있어요.',
  'vitk': '혈액 응고 지연으로 멍이 잘 들 수 있어요.',
  'vitb1': '피로, 식욕부진, 신경/근육 기능 저하(심하면 각기병) 위험이 있어요.',
  'vitb2': '구순염·구내염, 피부/눈 피로 같은 증상이 있을 수 있어요.',
  'vitb3': '피로, 피부/소화/신경 증상(심하면 펠라그라) 위험이 있어요.',
  'vitb6': '피부 트러블, 빈혈, 신경 과민 등이 있을 수 있어요.',
  'vitb12': '거대적혈모구성 빈혈, 손발저림, 기억력 저하가 있을 수 있어요.',
  'folate': '빈혈, 피로, 임신기 신경관 결손 위험 증가와 연관됩니다.',
  'biotin': '피부/모발 건강 저하, 피로감이 있을 수 있어요.',
  'pantothenic': '피로, 두통, 감각 이상 등이 보고됩니다.',
  'vita_rae': '야맹증, 눈·피부 건조, 면역 저하가 있을 수 있어요.',
};

// 각 영양소별 대표 음식 10개
// 형식: key -> List<Map>{name, portion, note, tags(List<String>)}
const Map<String, List<Map<String, dynamic>>> NUTRIENT_FOODS = {
  // ── 탄단지 ─────────────────────────────────────────────────────
  'chocdf': [
    {'name':'현미밥','portion':'150g','note':'복합탄수화물','tags':['곡류']},
    {'name':'오트밀','portion':'50g','note':'식이섬유 풍부','tags':['아침']},
    {'name':'고구마','portion':'150g','note':'GI 낮음','tags':['근채류']},
    {'name':'통밀빵','portion':'2장','note':'정제 곡물 대체','tags':['빵']},
    {'name':'퀴노아','portion':'100g','note':'단백질도 포함','tags':['곡류']},
    {'name':'보리/귀리밥','portion':'150g','note':'β-글루칸','tags':['곡류']},
    {'name':'바나나','portion':'1개','note':'운동 전후','tags':['과일']},
    {'name':'감자(구운)','portion':'150g','note':'포만감','tags':['근채류']},
    {'name':'현미떡','portion':'2~3조각','note':'간식 대체','tags':['간식']},
    {'name':'옥수수','portion':'1개','note':'통곡물','tags':['곡류']},
  ],
  'prot': [
    {'name':'닭가슴살','portion':'100g','note':'고단백·저지방','tags':['고단백']},
    {'name':'두부','portion':'150g','note':'식물성 단백질','tags':['식물성']},
    {'name':'달걀','portion':'2개','note':'완전 단백질','tags':['간편']},
    {'name':'그릭요거트','portion':'170g','note':'단백질+칼슘','tags':['간식']},
    {'name':'연어','portion':'120g','note':'오메가-3 + 단백질','tags':['생선']},
    {'name':'소고기(살코기)','portion':'120g','note':'철·B군 비타민','tags':['육류']},
    {'name':'렌틸콩','portion':'150g','note':'단백질+식이섬유','tags':['콩류']},
    {'name':'병아리콩','portion':'150g','note':'식물성 단백질','tags':['콩류']},
    {'name':'우유','portion':'200ml','note':'단백질+칼슘','tags':['유제품']},
    {'name':'참치(통조림 물)','portion':'100g','note':'간편 단백질','tags':['생선']},
  ],
  'fatce': [
    {'name':'아보카도','portion':'1/2개','note':'불포화지방','tags':['건강지방']},
    {'name':'올리브오일','portion':'1큰술','note':'샐러드/조리','tags':['조리']},
    {'name':'아몬드','portion':'25g','note':'비타민E 포함','tags':['견과']},
    {'name':'호두','portion':'25g','note':'ALA(오메가-3)','tags':['견과']},
    {'name':'고등어','portion':'120g','note':'오메가-3','tags':['생선']},
    {'name':'연어','portion':'120g','note':'EPA/DHA','tags':['생선']},
    {'name':'땅콩버터','portion':'1큰술','note':'불포화지방','tags':['스프레드']},
    {'name':'치아씨드','portion':'1큰술','note':'오메가-3+섬유','tags':['씨앗']},
    {'name':'해바라기씨','portion':'25g','note':'비타민E','tags':['씨앗']},
    {'name':'올리브','portion':'6~8알','note':'간식/토핑','tags':['올리브']},
  ],

  // ── 나머지(식이섬유/당류/포화/콜레스테롤) ─────────────────────────
  'fibtg': [
    {'name':'브로콜리','portion':'100g','note':'수용성 식이섬유','tags':['채소']},
    {'name':'강낭콩','portion':'150g','note':'포만감↑','tags':['콩류']},
    {'name':'귀리','portion':'50g','note':'베타글루칸','tags':['곡류']},
    {'name':'사과','portion':'1개','note':'펙틴','tags':['과일']},
    {'name':'치아씨드','portion':'1큰술','note':'오메가-3+섬유','tags':['씨앗']},
    {'name':'통밀빵','portion':'2장','note':'전곡립','tags':['빵']},
    {'name':'아마씨','portion':'1큰술','note':'오메가-3+섬유','tags':['씨앗']},
    {'name':'렌틸콩','portion':'150g','note':'단백질+섬유','tags':['콩류']},
    {'name':'배추김치(저염)','portion':'50g','note':'유산균+섬유','tags':['발효']},
    {'name':'배','portion':'1개','note':'수용성 섬유','tags':['과일']},
  ],
  'sugar': [
    {'name':'블루베리','portion':'100g','note':'천연 단맛+항산화','tags':['과일']},
    {'name':'딸기','portion':'150g','note':'상대적 당 낮음','tags':['과일']},
    {'name':'사과','portion':'1개','note':'섬유와 함께','tags':['과일']},
    {'name':'플레인요거트','portion':'170g','note':'무가당, 과일과','tags':['유제품']},
    {'name':'견과류 믹스','portion':'25g','note':'간식 대체','tags':['견과']},
    {'name':'당근 스틱','portion':'100g','note':'간식 대체','tags':['채소']},
    {'name':'고구마(구운)','portion':'100g','note':'천연 단맛','tags':['근채류']},
    {'name':'바나나(작은 크기)','portion':'1개','note':'운동 전후','tags':['과일']},
    {'name':'오렌지','portion':'1개','note':'비타민C+섬유','tags':['과일']},
    {'name':'토마토','portion':'150g','note':'당 낮고 포만감','tags':['채소']},
  ],
  'fasat': [
    {'name':'올리브오일','portion':'1큰술','note':'포화↓ 불포화↑','tags':['대체']},
    {'name':'아보카도','portion':'1/2개','note':'포화 낮은 과일','tags':['대체']},
    {'name':'연어','portion':'120g','note':'포화 낮고 오메가-3','tags':['생선']},
    {'name':'닭가슴살','portion':'100g','note':'붉은육류 대체','tags':['육류']},
    {'name':'두부','portion':'150g','note':'식물성 단백질','tags':['식물성']},
    {'name':'저지방우유','portion':'200ml','note':'지방 줄인 유제품','tags':['유제품']},
    {'name':'그릭요거트(저지방)','portion':'170g','note':'간식 대체','tags':['유제품']},
    {'name':'아몬드','portion':'25g','note':'불포화지방','tags':['견과']},
    {'name':'해바라기씨','portion':'25g','note':'불포화지방','tags':['씨앗']},
    {'name':'올리브','portion':'6~8알','note':'샐러드 토핑','tags':['올리브']},
  ],
  'chole': [
    {'name':'달걀노른자','portion':'1~2개','note':'콜레스테롤 풍부(과다 주의)','tags':['계란']},
    {'name':'간(소/닭)','portion':'60g','note':'내장류, 매우 높음','tags':['육류']},
    {'name':'새우','portion':'100g','note':'해산물 콜레스테롤','tags':['해산물']},
    {'name':'오징어','portion':'100g','note':'해산물 콜레스테롤','tags':['해산물']},
    {'name':'정어리','portion':'120g','note':'등푸른 생선','tags':['생선']},
    {'name':'치즈','portion':'30g','note':'유제품 콜레스테롤','tags':['유제품']},
    {'name':'버터','portion':'10g','note':'유지방, 포화지방 동반','tags':['유제품']},
    {'name':'가리비/조개류','portion':'80g','note':'조개류, 중간 이상','tags':['해산물']},
    {'name':'닭껍질','portion':'40g','note':'지방/콜레스테롤','tags':['육류']},
    {'name':'크림(생크림)','portion':'30ml','note':'유지방','tags':['유제품']},
  ],

  // ── 비타민 ─────────────────────────────────────────────────────
  'vita_rae': [
    {'name':'당근','portion':'100g','note':'베타카로틴','tags':['채소']},
    {'name':'고구마','portion':'150g','note':'A 전구체','tags':['근채류']},
    {'name':'시금치','portion':'100g','note':'지용성: 지방과','tags':['채소']},
    {'name':'케일','portion':'70g','note':'카로티노이드','tags':['채소']},
    {'name':'단호박','portion':'150g','note':'카로틴','tags':['근채류']},
    {'name':'파프리카(주황)','portion':'100g','note':'카로틴','tags':['채소']},
    {'name':'계란노른자','portion':'1~2개','note':'레티놀 소량','tags':['계란']},
    {'name':'고수/파슬리','portion':'20g','note':'허브 카로틴','tags':['허브']},
    {'name':'망고','portion':'1개','note':'카로틴 과일','tags':['과일']},
    {'name':'살구(건조)','portion':'30g','note':'건과류 카로틴','tags':['과일']},
  ],
  'vitc': [
    {'name':'키위','portion':'1개','note':'C 풍부','tags':['과일']},
    {'name':'파프리카(빨강)','portion':'100g','note':'가열 안정성↑','tags':['채소']},
    {'name':'딸기','portion':'150g','note':'항산화','tags':['과일']},
    {'name':'오렌지','portion':'1개','note':'감귤류','tags':['과일']},
    {'name':'브로콜리','portion':'100g','note':'데치기','tags':['채소']},
    {'name':'자두/복숭아','portion':'1개','note':'계절 과일','tags':['과일']},
    {'name':'양배추','portion':'100g','note':'비타민C 소량','tags':['채소']},
    {'name':'구아바','portion':'100g','note':'C 매우 풍부','tags':['과일']},
    {'name':'파인애플','portion':'100g','note':'효소+비타민C','tags':['과일']},
    {'name':'감(연시)','portion':'1개','note':'가을 제철','tags':['과일']},
  ],
  'vitd': [
    {'name':'연어','portion':'120g','note':'D3 최고급원','tags':['생선']},
    {'name':'고등어','portion':'120g','note':'오메가-3 + D','tags':['생선']},
    {'name':'참치(통조림)','portion':'100g','note':'간편 보충','tags':['생선']},
    {'name':'계란노른자','portion':'1~2개','note':'소량 포함','tags':['계란']},
    {'name':'버섯(햇빛건조)','portion':'100g','note':'식물성 D2','tags':['채소']},
    {'name':'강화우유','portion':'200ml','note':'강화 식품','tags':['유제품']},
    {'name':'강화 두유','portion':'200ml','note':'비건 대체','tags':['식물성']},
    {'name':'정어리','portion':'120g','note':'작은 생선','tags':['생선']},
    {'name':'청어','portion':'120g','note':'지방 많은 생선','tags':['생선']},
    {'name':'표고버섯(건조)','portion':'15g','note':'햇빛 쬐면↑','tags':['채소']},
  ],
  'vitb1': [
    {'name':'돼지고기 등심','portion':'100g','note':'티아민 풍부','tags':['육류']},
    {'name':'해바라기씨','portion':'25g','note':'간식/토핑','tags':['씨앗']},
    {'name':'강낭콩','portion':'150g','note':'B1 보충','tags':['콩류']},
    {'name':'현미','portion':'150g','note':'정제 대신 전곡','tags':['곡류']},
    {'name':'감자','portion':'150g','note':'B1 소량','tags':['근채류']},
    {'name':'참깨','portion':'1큰술','note':'씨앗류 B1','tags':['씨앗']},
    {'name':'피스타치오','portion':'25g','note':'견과 B1','tags':['견과']},
    {'name':'완두콩','portion':'150g','note':'콩류 B1','tags':['콩류']},
    {'name':'아스파라거스','portion':'100g','note':'봄철 채소','tags':['채소']},
    {'name':'돼지간','portion':'60g','note':'고함량(과다 주의)','tags':['육류']},
  ],
  'vitb2': [
    {'name':'우유','portion':'200ml','note':'리보플라빈','tags':['유제품']},
    {'name':'요거트','portion':'170g','note':'간편','tags':['유제품']},
    {'name':'치즈','portion':'30g','note':'소량 보충','tags':['유제품']},
    {'name':'달걀','portion':'2개','note':'B2 포함','tags':['계란']},
    {'name':'아몬드','portion':'25g','note':'식물성 B2','tags':['견과']},
    {'name':'간(소/닭)','portion':'60g','note':'고함량(주의)','tags':['육류']},
    {'name':'표고버섯','portion':'100g','note':'소량 포함','tags':['채소']},
    {'name':'정어리','portion':'120g','note':'해산물 B2','tags':['생선']},
    {'name':'시금치','portion':'100g','note':'녹채류 B군','tags':['채소']},
    {'name':'참깨','portion':'1큰술','note':'씨앗류 B2','tags':['씨앗']},
  ],
  'vitb3': [
    {'name':'닭가슴살','portion':'100g','note':'니아신 풍부','tags':['육류']},
    {'name':'참치(통조림)','portion':'100g','note':'니아신+단백질','tags':['생선']},
    {'name':'땅콩','portion':'25g','note':'식물성 B3','tags':['견과']},
    {'name':'버섯','portion':'100g','note':'B3 소량','tags':['채소']},
    {'name':'현미','portion':'150g','note':'곡류 B3','tags':['곡류']},
    {'name':'연어','portion':'120g','note':'해산물 B3','tags':['생선']},
    {'name':'쇠고기','portion':'100g','note':'육류 B3','tags':['육류']},
    {'name':'감자','portion':'150g','note':'근채류 B3','tags':['근채류']},
    {'name':'완두콩','portion':'150g','note':'콩류 B3','tags':['콩류']},
    {'name':'해바라기씨','portion':'25g','note':'씨앗류 B3','tags':['씨앗']},
  ],
  'vitb6': [
    {'name':'바나나','portion':'1개','note':'B6 간편 보충','tags':['과일']},
    {'name':'감자','portion':'150g','note':'B6 포함','tags':['근채류']},
    {'name':'닭가슴살','portion':'100g','note':'단백질+B6','tags':['육류']},
    {'name':'병아리콩','portion':'150g','note':'식물성 B6','tags':['콩류']},
    {'name':'연어','portion':'120g','note':'해산물 B6','tags':['생선']},
    {'name':'아보카도','portion':'1/2개','note':'과일 B6','tags':['과일']},
    {'name':'시금치','portion':'100g','note':'녹채류 B6','tags':['채소']},
    {'name':'피스타치오','portion':'25g','note':'견과 B6','tags':['견과']},
    {'name':'참깨','portion':'1큰술','note':'씨앗 B6','tags':['씨앗']},
    {'name':'현미','portion':'150g','note':'곡류 B6','tags':['곡류']},
  ],
  'vitb12': [
    {'name':'조개류','portion':'80g','note':'B12 최고급원','tags':['해산물']},
    {'name':'연어','portion':'120g','note':'B12 + 오메가-3','tags':['생선']},
    {'name':'참치','portion':'120g','note':'해산물 B12','tags':['생선']},
    {'name':'우유','portion':'200ml','note':'유제품 B12','tags':['유제품']},
    {'name':'요거트','portion':'170g','note':'간편 보충','tags':['유제품']},
    {'name':'치즈','portion':'30g','note':'소량 보충','tags':['유제품']},
    {'name':'달걀','portion':'1~2개','note':'비건 제외시 OK','tags':['계란']},
    {'name':'정어리','portion':'120g','note':'작은 생선','tags':['생선']},
    {'name':'소간','portion':'60g','note':'고함량(주의)','tags':['육류']},
    {'name':'강화두유','portion':'200ml','note':'식물성 강화','tags':['식물성']},
  ],
  'folate': [
    {'name':'시금치','portion':'100g','note':'엽산 풍부','tags':['채소']},
    {'name':'아보카도','portion':'1/2개','note':'엽산 + 건강지방','tags':['과일']},
    {'name':'렌틸콩','portion':'150g','note':'엽산 + 단백질','tags':['콩류']},
    {'name':'브로콜리','portion':'100g','note':'데쳐서','tags':['채소']},
    {'name':'아스파라거스','portion':'100g','note':'봄철 채소','tags':['채소']},
    {'name':'병아리콩','portion':'150g','note':'콩류 엽산','tags':['콩류']},
    {'name':'오렌지','portion':'1개','note':'감귤류 엽산','tags':['과일']},
    {'name':'비트','portion':'100g','note':'근채류 엽산','tags':['근채류']},
    {'name':'케일','portion':'70g','note':'녹채류 엽산','tags':['채소']},
    {'name':'강화 곡물','portion':'30~50g','note':'시리얼/빵','tags':['곡류']},
  ],

  // ── 무기질 ─────────────────────────────────────────────────────
  'na': [
    {'name':'방울토마토','portion':'150g','note':'자연식으로 나트륨↓','tags':['저나트륨']},
    {'name':'오이','portion':'150g','note':'수분+저나트륨','tags':['채소']},
    {'name':'구운감자(무염)','portion':'150g','note':'무가염 조리','tags':['근채류']},
    {'name':'플레인요거트','portion':'170g','note':'가공소금 적음','tags':['유제품']},
    {'name':'바나나','portion':'1개','note':'칼륨과 균형','tags':['과일']},
    {'name':'찐 단호박','portion':'150g','note':'자연 단맛','tags':['근채류']},
    {'name':'사과','portion':'1개','note':'가공 대신 과일','tags':['과일']},
    {'name':'무염 견과','portion':'25g','note':'간식 대체','tags':['견과']},
    {'name':'무염 두부구이','portion':'150g','note':'양념 최소화','tags':['식물성']},
    {'name':'삶은 달걀(무염)','portion':'1~2개','note':'소금 없이','tags':['계란']},
  ],
  'k': [
    {'name':'바나나','portion':'1개','note':'칼륨 풍부','tags':['과일']},
    {'name':'시금치','portion':'100g','note':'칼륨+엽산','tags':['채소']},
    {'name':'감자','portion':'150g','note':'구우면 좋아요','tags':['근채류']},
    {'name':'아보카도','portion':'1/2개','note':'칼륨+지방','tags':['과일']},
    {'name':'강낭콩','portion':'150g','note':'칼륨+섬유','tags':['콩류']},
    {'name':'연시/감','portion':'1개','note':'가을 제철','tags':['과일']},
    {'name':'주키니 호박','portion':'150g','note':'칼륨 공급','tags':['채소']},
    {'name':'고구마','portion':'150g','note':'베타카로틴도','tags':['근채류']},
    {'name':'비트','portion':'100g','note':'질산염+칼륨','tags':['근채류']},
    {'name':'토마토','portion':'150g','note':'칼륨+리코펜','tags':['채소']},
  ],
  'p': [
    {'name':'멸치볶음','portion':'15g','note':'인·칼슘 풍부','tags':['반찬']},
    {'name':'치즈','portion':'30g','note':'유제품 인 풍부','tags':['유제품']},
    {'name':'우유','portion':'200ml','note':'인 + 칼슘','tags':['유제품']},
    {'name':'요거트','portion':'170g','note':'유제품 인 공급','tags':['유제품']},
    {'name':'연어','portion':'120g','note':'생선 인 풍부','tags':['생선']},
    {'name':'닭가슴살','portion':'100g','note':'단백질과 함께','tags':['육류']},
    {'name':'돼지고기(살코기)','portion':'100g','note':'인 + 단백질','tags':['육류']},
    {'name':'두부','portion':'150g','note':'식물성 인','tags':['대체']},
    {'name':'렌틸콩','portion':'150g','note':'콩류 인 풍부','tags':['콩류']},
    {'name':'해바라기씨','portion':'25g','note':'씨앗류 인','tags':['씨앗']},
  ],
  'mg': [
    {'name':'아몬드','portion':'25g','note':'마그네슘 풍부','tags':['견과']},
    {'name':'호박씨','portion':'25g','note':'Mg+아연','tags':['씨앗']},
    {'name':'시금치','portion':'100g','note':'Mg+엽산','tags':['채소']},
    {'name':'다크초콜릿(70%↑)','portion':'20g','note':'간식으로 소량','tags':['간식']},
    {'name':'귀리','portion':'50g','note':'곡류 기반 Mg','tags':['곡류']},
    {'name':'캐슈넛','portion':'25g','note':'견과류 Mg','tags':['견과']},
    {'name':'검은콩','portion':'150g','note':'콩류 Mg','tags':['콩류']},
    {'name':'바나나','portion':'1개','note':'과일 Mg','tags':['과일']},
    {'name':'두부','portion':'150g','note':'식물성 Mg','tags':['대체']},
    {'name':'브로콜리','portion':'100g','note':'채소 Mg','tags':['채소']},
  ],
  'ca': [
    {'name':'우유','portion':'200ml','note':'칼슘 기본식품','tags':['유제품']},
    {'name':'요거트','portion':'170g','note':'흡수율↑','tags':['유제품']},
    {'name':'치즈','portion':'30g','note':'간편 보충','tags':['유제품']},
    {'name':'두부','portion':'150g','note':'식물성 칼슘','tags':['대체']},
    {'name':'멸치볶음','portion':'15g','note':'칼슘+단백질','tags':['반찬']},
    {'name':'케일','portion':'70g','note':'비타민K도 함께','tags':['채소']},
    {'name':'청경채','portion':'100g','note':'흡수 좋은 녹색채소','tags':['채소']},
    {'name':'그릭요거트','portion':'170g','note':'단백질+칼슘','tags':['유제품']},
    {'name':'강화두유','portion':'200ml','note':'강화 칼슘','tags':['식물성']},
    {'name':'참깨','portion':'1큰술','note':'칼슘 포함','tags':['씨앗']},
  ],
  'fe': [
    {'name':'소고기(살코기)','portion':'100g','note':'헤므철','tags':['육류']},
    {'name':'간(소/닭)','portion':'60g','note':'철 최고급원(과다 주의)','tags':['육류']},
    {'name':'굴','portion':'80g','note':'철+아연','tags':['해산물']},
    {'name':'시금치','portion':'100g','note':'비헴철+비타민C와','tags':['채소']},
    {'name':'렌틸콩','portion':'150g','note':'철+단백질','tags':['콩류']},
    {'name':'병아리콩','portion':'150g','note':'식물성 철','tags':['콩류']},
    {'name':'호박씨','portion':'25g','note':'스낵/토핑','tags':['씨앗']},
    {'name':'두부','portion':'150g','note':'식물성 철 보충','tags':['대체']},
    {'name':'퀴노아','portion':'100g','note':'철+단백질','tags':['곡류']},
    {'name':'검은깨','portion':'1큰술','note':'비헴철 소량','tags':['씨앗']},
  ],
  'zn': [
    {'name':'굴','portion':'80g','note':'아연 최고급원','tags':['해산물']},
    {'name':'쇠고기','portion':'100g','note':'흡수율 높음','tags':['육류']},
    {'name':'돼지고기','portion':'100g','note':'아연 공급','tags':['육류']},
    {'name':'호박씨','portion':'25g','note':'식물성 아연','tags':['씨앗']},
    {'name':'병아리콩','portion':'150g','note':'식물성 아연','tags':['콩류']},
    {'name':'치즈','portion':'30g','note':'유제품 아연','tags':['유제품']},
    {'name':'요거트','portion':'170g','note':'유제품 아연','tags':['유제품']},
    {'name':'게/새우','portion':'120g','note':'해산물 아연','tags':['해산물']},
    {'name':'아몬드','portion':'25g','note':'견과 아연','tags':['견과']},
    {'name':'통밀빵','portion':'2장','note':'곡류 아연','tags':['빵']},
  ],
};
